---
name: Lint Commit Messages

on:  # yamllint disable-line rule:truthy
  pull_request:  # yamllint disable-line rule:truthy

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
